//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: LaserPub.ice
//  Source: LaserPub.idsl
//
//******************************************************************
#ifndef ROBOCOMPLASERPUB_ICE
#define ROBOCOMPLASERPUB_ICE
#include <Laser.ice>
module RoboCompLaserPub
{
	interface LaserPub
	{
		idempotent void pushLaserData (RoboCompLaser::TLaserData laserData);
	};
};

#endif
