//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: OmniRobotPub.ice
//  Source: OmniRobotPub.idsl
//
//******************************************************************
#ifndef ROBOCOMPOMNIROBOTPUB_ICE
#define ROBOCOMPOMNIROBOTPUB_ICE
#include <GenericBase.ice>
module RoboCompOmniRobotPub
{
	interface OmniRobotPub
	{
		void pushBaseState (RoboCompGenericBase::TBaseState state);
	};
};

#endif
